version: '3.4'

name: apitest

networks:
  backend:

services:
  api:
    image: apitest
    container_name: apitest
    build:
      dockerfile: ApiTest/Dockerfile
      context: .
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "17000:8080"
      - "17006:8090"
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: apitest_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apitest
    volumes:
      - ./docker/mount/pgsql:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: apitest_pgadmin
    user: root
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "17001:80"
    volumes:
      - ./docker/mount/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: apitest_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 17002:15672
      - 17003:5672
    volumes:
      - ./docker/mount/rabbitmq:/var/lib/rabbitmq
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    container_name: apitest_mailhog
    restart: always
    ports:
      - "17004:8025"
      - "17005:1025"
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    container_name: apitest_redis
    restart: always
    ports:
      - "17007:6739"
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    volumes:
      - ./docker/mount/redis/data:/data
    networks:
      - backend
