version: '3.4'

name: apitest

networks:
  backend:

services:
  api:
    image: apitest
    container_name: apitest
    build:
      dockerfile: ApiTest/Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "17000:8080"
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: apitest_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apitest
    volumes:
      - ./docker/mount/pgsql:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:7.7
    container_name: apitest_pgadmin
    user: root
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "17001:80"
    volumes:
      - ./docker/mount/pgadmin:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - backend
